#spring.datasource.url=jdbc:mysql://localhost:3306/keepers
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#
#

spring.jpa.database=POSTGRESQL
spring.datasource.url= jdbc:postgresql://localhost:5432/keeper
spring.datasource.username= postgres
spring.datasource.password= welcome
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update